# Generated by Django 3.1.2 on 2020-10-28 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lighsticks',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Item is still available'), ('SOLD', 'Item has been sold'), ('RESTOCKING', 'Item will be restocked in a few days')], default='SOLD', max_length=10),
        ),
        migrations.AlterField(
            model_name='merchandises',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Item is still available'), ('SOLD', 'Item has been sold'), ('RESTOCKING', 'Item will be restocked in a few days')], default='SOLD', max_length=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Item is still available'), ('SOLD', 'Item has been sold'), ('RESTOCKING', 'Item will be restocked in a few days')], default='SOLD', max_length=10),
        ),
    ]
