# Generated by Django 3.1.2 on 2020-10-28 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20201028_1303'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lighsticks',
            new_name='Lightsticks',
        ),
        migrations.RenameModel(
            old_name='Ticket',
            new_name='Tickets',
        ),
    ]
